# Generated by Django 4.2.19 on 2025-03-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='categroy',
            new_name='categroy_id',
        ),
    ]
