# Generated by Django 4.2.19 on 2025-03-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_categroy_sub_category_categroy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='categroy_id',
            new_name='categroy',
        ),
    ]
